name: Update SVG

on:
  schedule:
    - cron: '0 0 * * *'  # Adjust the schedule as needed
  workflow_dispatch:

jobs:
 
        echo "FOLLOWERS=$FOLLOWERS" >> $GITHUB_ENV

    - name: Replace placeholders in SVG files with fetched data
      run: |
        sed -i "s/{{AGE_DATA}}/$AGE_DATA/g" dark_mode.svg
        sed -i "s/{{STARS}}/$STARS/g" dark_mode.svg
        sed -i "s/{{REPOS}}/$REPOS/g" dark_mode.svg
        sed -i "s/{{COMMITS}}/$COMMITS/g" dark_mode.svg
        sed -i "s/{{FOLLOWERS}}/$FOLLOWERS/g" dark_mode.svg
        sed -i update-svg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run "s/{{AGE_DATA}}/$AGE_DATA/g" light_mode.svg
        sed -i "s/{{STARS}}/$STARS/g" light_mode.svg
        sed -i "s/{{REPOS}}/$REPOS/g" light_mode.svg
        sed: pip install requests jq

      - name: Fetch data from GitHub API
        run: |
          AGE_DATA=$(curl -s "https://api.github.com/users/MayankSuthar1" | jq -r '.created_at')
          STARS=$(curl -s "https://api.github.com/users/MayankSuthar1/repos" | jq '[.[].stargazers_count] | add // 0')
          REPOS=$(curl -s "https://api.github.com/users/MayankSuthar1/repos" | jq 'length')
          COMMITS -i "s/{{COMMITS}}/$COMMITS/g" light_mode.svg
        sed -i "s/{{FOLLOWERS}}/$FOLLOWERS/g" light_mode.svg

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github=$(curl -s "https://api.github.com/users/MayankSuthar1/events" | jq '[.[].payload.commits // []] | add | length')
          FOLLOWERS=$(curl -s ".com"
        git add dark_mode.svg light_mode.svg
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          git commit -m "Update SVG with dynamic data"
          git push
        fi
